#SERVER_URL = 'https://fhnpi.openbiomaps.org'
#SERVER_URL = 'http://milvus.openbiomaps.org'
SERVER_URL = 'http://obm.bfnp.hu/'
PROJECT = 'BFNPI kollektor'
#PROJECT = 'Fertő-Hanság Nemzeti Park biotikai adatbázisa'
#PROJECT = 'OpenBirdMaps'
#PROJECT = 'Eco-Logic Consulting'
