#SERVER_URL = 'https://fhnpi.openbiomaps.org'
SERVER_URL = 'http://milvus.openbiomaps.org'
#PROJECT = 'Fertő-Hanság Nemzeti Park biotikai adatbázisa'
#PROJECT = 'OpenBirdMaps'
PROJECT = 'Eco-Logic Consulting'
